project_with_db/SahuTechProject/ContactApp/urls.py
from django.urls import path

from . import views

app_name='ContactApp'
urlpatterns = [
    path('', views.contact_home, name='contact-home'),
    path('contact-us', views.contact_us, name='contact-us'),
    path('form-details', views.form_details, name='form-details'),
    path('form-home-details', views.form_home_details, name='form-home-details'),
]

project_with_db/SahuTechProject/SahuTechProject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('ContactApp.urls')),
]

project_with_db/SahuTechProject/ContactApp/models.py
from django.db import models

# Create your models here.
class ContactUs(models.Model):
    name = models.CharField(max_length=30)
    email = models.CharField(max_length=30)
    phone = models.CharField(max_length=30, blank=True)
    message = models.CharField(max_length=300, blank=True)

    def __str__(self):
        return self.name

project_with_db/SahuTechProject/ContactApp/views.py
from django.shortcuts import render, redirect
from ContactApp.models import ContactUs
from django.contrib import messages

# Create your views here.
def contact_home(request):
    return render(request, 'web.html')

def contact_us(request):
    return render(request, 'ContactUs.html')

def form_details(request):
    if request.method == 'POST':
        name1 = request.POST['name']
        email1 = request.POST['email']
        message1 = request.POST['message']

        contact_us_obj = ContactUs.objects.create(
            name=name1,
            email=email1,
            message=message1
        )
        contact_us_obj.save()
        messages.success(request, 'Your Message was sent successfully!')
        return redirect('ContactApp:contact-us')

def form_home_details(request):
    if request.method == 'POST':
        name1 = request.POST['name']
        email1 = request.POST['email']
        phone1 = request.POST['phone']

        contact_us_obj = ContactUs.objects.create(
            name=name1,
            email=email1,
            phone=phone1
        )
        contact_us_obj.save()
        messages.success(request, 'Your Message was sent successfully!')
        return redirect('ContactApp:contact-home')

project_with_db/SahuTechProject/templates/ContactUs.html
{% load static %}
<!DOCTYPE html>
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<title>SAHU Contact Page</title>
		<meta name="HandheldFriendly" content="True">
		<meta name="MobileOptimized" content="320">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<link rel="preconnect" >
<link  rel="stylesheet"><link rel="stylesheet" type="text/css" href="{% static './screen.css' %}">
		<link rel="canonical">
    <meta name="referrer" content="no-referrer-when-downgrade">
    <meta name="generator" content="Ghost 4.0">
    </head>

<body>
	<div class="section-page-custom flex">
		<div>
			<a>
				<img src="{% static 'cimg.jpg' %}">
			</a>
		</div>
		<div>
			<div class="page-custom-header">
				<a href="{% url 'ContactApp:contact-home' %}">Back to Homepage</a>
			</div>
			<div class="page-custom-content flex">
				<div class="subscribe-wrap contact-wrap">
					<a>
						<img src="{% static 'Logo.png' %}" alt="Denteur Logo">
					  </a>
					<h3>Contact Us</h3>
				
					<form method="POST" action="{% url 'ContactApp:form-details' %}">
						{% csrf_token %}
						<input class="subscribe-input contact-name" required="" type="text" name="name" placeholder="Your name">
						<input class="subscribe-input contact-email" required="" type="email" name="email" placeholder="Your email address">
						<input class="subscribe-input contact-message" required="" name="message" placeholder="Your message"><br>
						<button class="global-button" type="submit">Send message</button>
					</form>
				</div>
				{% if messages %}
                                {% for message in messages %}
				                          {{message}}
                                {% endfor %}
				{% endif %}
			</div>
			<div class="page-custom-footer">
				<a>Denteur.</a>
				<span>For a healthy smile.</span>
			</div>
		</div>
	</div>

</body></html>